[package]
name = "fit-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = "4.4.7"
egui = "0.23.0"
eframe = "0.23.0"
image = "0.24.7"
